# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tiny Analyst' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TwoWayBondage'
  pod 'Alamofire'

  # Pods for Tiny Analyst

end
